<?php

namespace AppBundle\Repository;

/**
 * QboCustomersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QboCustomersRepository extends \Doctrine\ORM\EntityRepository
{
}
