<?php

namespace AppBundle\Repository;

/**
 * QboEmployeesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QboEmployeesRepository extends \Doctrine\ORM\EntityRepository
{
}
