<?php

namespace AppBundle\Repository;

/**
 * QboItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QboItemsRepository extends \Doctrine\ORM\EntityRepository
{
}
