<?php

namespace AppBundle\Repository;

/**
 * QBOTokensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QBOTokensRepository extends \Doctrine\ORM\EntityRepository
{
}
