app:
  resource: '@AppBundle/Controller/API/QBOAPI'
  type: annotation
  prefix:   /api/v1
  #defaults: {_format:json}

QBOAuth:
  resource: '@AppBundle/Controller/API/QBOAuth'
  type: annotation
  prefix:   /